require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CityweathersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Cityweather. As you add validations to Cityweather, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CityweathersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all cityweathers as @cityweathers" do
      cityweather = Cityweather.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:cityweathers)).to eq([cityweather])
    end
  end

  describe "GET #show" do
    it "assigns the requested cityweather as @cityweather" do
      cityweather = Cityweather.create! valid_attributes
      get :show, {:id => cityweather.to_param}, valid_session
      expect(assigns(:cityweather)).to eq(cityweather)
    end
  end

  describe "GET #new" do
    it "assigns a new cityweather as @cityweather" do
      get :new, {}, valid_session
      expect(assigns(:cityweather)).to be_a_new(Cityweather)
    end
  end

  describe "GET #edit" do
    it "assigns the requested cityweather as @cityweather" do
      cityweather = Cityweather.create! valid_attributes
      get :edit, {:id => cityweather.to_param}, valid_session
      expect(assigns(:cityweather)).to eq(cityweather)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Cityweather" do
        expect {
          post :create, {:cityweather => valid_attributes}, valid_session
        }.to change(Cityweather, :count).by(1)
      end

      it "assigns a newly created cityweather as @cityweather" do
        post :create, {:cityweather => valid_attributes}, valid_session
        expect(assigns(:cityweather)).to be_a(Cityweather)
        expect(assigns(:cityweather)).to be_persisted
      end

      it "redirects to the created cityweather" do
        post :create, {:cityweather => valid_attributes}, valid_session
        expect(response).to redirect_to(Cityweather.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved cityweather as @cityweather" do
        post :create, {:cityweather => invalid_attributes}, valid_session
        expect(assigns(:cityweather)).to be_a_new(Cityweather)
      end

      it "re-renders the 'new' template" do
        post :create, {:cityweather => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cityweather" do
        cityweather = Cityweather.create! valid_attributes
        put :update, {:id => cityweather.to_param, :cityweather => new_attributes}, valid_session
        cityweather.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested cityweather as @cityweather" do
        cityweather = Cityweather.create! valid_attributes
        put :update, {:id => cityweather.to_param, :cityweather => valid_attributes}, valid_session
        expect(assigns(:cityweather)).to eq(cityweather)
      end

      it "redirects to the cityweather" do
        cityweather = Cityweather.create! valid_attributes
        put :update, {:id => cityweather.to_param, :cityweather => valid_attributes}, valid_session
        expect(response).to redirect_to(cityweather)
      end
    end

    context "with invalid params" do
      it "assigns the cityweather as @cityweather" do
        cityweather = Cityweather.create! valid_attributes
        put :update, {:id => cityweather.to_param, :cityweather => invalid_attributes}, valid_session
        expect(assigns(:cityweather)).to eq(cityweather)
      end

      it "re-renders the 'edit' template" do
        cityweather = Cityweather.create! valid_attributes
        put :update, {:id => cityweather.to_param, :cityweather => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested cityweather" do
      cityweather = Cityweather.create! valid_attributes
      expect {
        delete :destroy, {:id => cityweather.to_param}, valid_session
      }.to change(Cityweather, :count).by(-1)
    end

    it "redirects to the cityweathers list" do
      cityweather = Cityweather.create! valid_attributes
      delete :destroy, {:id => cityweather.to_param}, valid_session
      expect(response).to redirect_to(cityweathers_url)
    end
  end

end
